/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface LupiInterface extends utils.Interface {
  contractName: "Lupi";
  functions: {
    "commitGuess(bytes32)": FunctionFragment;
    "endGame()": FunctionFragment;
    "getCommittedGuessHash()": FunctionFragment;
    "getGuessCounter()": FunctionFragment;
    "getLowestGuess()": FunctionFragment;
    "getRevealedGuess()": FunctionFragment;
    "getSaltedHash(uint32,bytes32)": FunctionFragment;
    "getWinner()": FunctionFragment;
    "newGame()": FunctionFragment;
    "revealGuess(uint32,bytes32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "commitGuess",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "endGame", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getCommittedGuessHash",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGuessCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLowestGuess",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRevealedGuess",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSaltedHash",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getWinner", values?: undefined): string;
  encodeFunctionData(functionFragment: "newGame", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "revealGuess",
    values: [BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "commitGuess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "endGame", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCommittedGuessHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGuessCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLowestGuess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRevealedGuess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSaltedHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getWinner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "newGame", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revealGuess",
    data: BytesLike
  ): Result;

  events: {};
}

export interface Lupi extends BaseContract {
  contractName: "Lupi";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: LupiInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    commitGuess(
      guessHash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    endGame(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getCommittedGuessHash(overrides?: CallOverrides): Promise<[string]>;

    getGuessCounter(
      overrides?: CallOverrides
    ): Promise<[number] & { counter: number }>;

    getLowestGuess(overrides?: CallOverrides): Promise<[BigNumber]>;

    getRevealedGuess(overrides?: CallOverrides): Promise<[BigNumber[]]>;

    getSaltedHash(
      guessData: BigNumberish,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getWinner(overrides?: CallOverrides): Promise<[string]>;

    newGame(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    revealGuess(
      answer: BigNumberish,
      salt: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  commitGuess(
    guessHash: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  endGame(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getCommittedGuessHash(overrides?: CallOverrides): Promise<string>;

  getGuessCounter(overrides?: CallOverrides): Promise<number>;

  getLowestGuess(overrides?: CallOverrides): Promise<BigNumber>;

  getRevealedGuess(overrides?: CallOverrides): Promise<BigNumber[]>;

  getSaltedHash(
    guessData: BigNumberish,
    salt: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  getWinner(overrides?: CallOverrides): Promise<string>;

  newGame(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  revealGuess(
    answer: BigNumberish,
    salt: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    commitGuess(guessHash: BytesLike, overrides?: CallOverrides): Promise<void>;

    endGame(overrides?: CallOverrides): Promise<void>;

    getCommittedGuessHash(overrides?: CallOverrides): Promise<string>;

    getGuessCounter(overrides?: CallOverrides): Promise<number>;

    getLowestGuess(overrides?: CallOverrides): Promise<BigNumber>;

    getRevealedGuess(overrides?: CallOverrides): Promise<BigNumber[]>;

    getSaltedHash(
      guessData: BigNumberish,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    getWinner(overrides?: CallOverrides): Promise<string>;

    newGame(overrides?: CallOverrides): Promise<void>;

    revealGuess(
      answer: BigNumberish,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    commitGuess(
      guessHash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    endGame(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getCommittedGuessHash(overrides?: CallOverrides): Promise<BigNumber>;

    getGuessCounter(overrides?: CallOverrides): Promise<BigNumber>;

    getLowestGuess(overrides?: CallOverrides): Promise<BigNumber>;

    getRevealedGuess(overrides?: CallOverrides): Promise<BigNumber>;

    getSaltedHash(
      guessData: BigNumberish,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getWinner(overrides?: CallOverrides): Promise<BigNumber>;

    newGame(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    revealGuess(
      answer: BigNumberish,
      salt: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    commitGuess(
      guessHash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    endGame(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getCommittedGuessHash(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getGuessCounter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getLowestGuess(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getRevealedGuess(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getSaltedHash(
      guessData: BigNumberish,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getWinner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    newGame(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    revealGuess(
      answer: BigNumberish,
      salt: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
