/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface LupiInterface extends utils.Interface {
  contractName: "Lupi";
  functions: {
    "commitGuess(int256)": FunctionFragment;
    "endGame()": FunctionFragment;
    "getGuessCounter()": FunctionFragment;
    "getLowestGuess()": FunctionFragment;
    "getWinner()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "commitGuess",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "endGame", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getGuessCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLowestGuess",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getWinner", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "commitGuess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "endGame", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getGuessCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLowestGuess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getWinner", data: BytesLike): Result;

  events: {};
}

export interface Lupi extends BaseContract {
  contractName: "Lupi";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: LupiInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    commitGuess(
      guess: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    endGame(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getGuessCounter(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { counter: BigNumber }>;

    getLowestGuess(overrides?: CallOverrides): Promise<[BigNumber]>;

    getWinner(overrides?: CallOverrides): Promise<[string]>;
  };

  commitGuess(
    guess: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  endGame(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getGuessCounter(overrides?: CallOverrides): Promise<BigNumber>;

  getLowestGuess(overrides?: CallOverrides): Promise<BigNumber>;

  getWinner(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    commitGuess(guess: BigNumberish, overrides?: CallOverrides): Promise<void>;

    endGame(overrides?: CallOverrides): Promise<void>;

    getGuessCounter(overrides?: CallOverrides): Promise<BigNumber>;

    getLowestGuess(overrides?: CallOverrides): Promise<BigNumber>;

    getWinner(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    commitGuess(
      guess: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    endGame(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getGuessCounter(overrides?: CallOverrides): Promise<BigNumber>;

    getLowestGuess(overrides?: CallOverrides): Promise<BigNumber>;

    getWinner(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    commitGuess(
      guess: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    endGame(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getGuessCounter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getLowestGuess(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getWinner(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
